services:
  - type: web
    name: emergenza-it-bot
    runtime: node
    buildCommand: rm -rf node_modules && npm install --build-from-source=sqlite3
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: TOKEN
        sync: false
      - key: CLIENT_ID
        sync: false
      - key: GUILD_ID
        sync: false
      - key: AI_RESPONSE_API_KEY
        sync: false
      - key: AI_MODERATION_API_KEY
        sync: false
